### ISSUE TITLE
JPA entities 

### ISSUE THREAD

**Issue by AdnanArch** [springframeworkguru/spring-6-webapp#16]
I followed the same process for adding Entities but i am not a able to add @Entity annotation in the class.

![entity](https://github.com/springframeworkguru/spring-6-webapp/assets/101959670/e23466b3-f4d6-4fbf-bda7-721cfcd76b80)

and in the project structure i am seeing these errors

![error](https://github.com/springframeworkguru/spring-6-webapp/assets/101959670/7d671d8b-9261-4aea-aadf-a39198dfea7c)

and also seeing these warnings in the maven file. 

![warnings](https://github.com/springframeworkguru/spring-6-webapp/assets/101959670/7f847c54-3403-49da-8540-a2684925f7be)

help me fixing these issues.

**Comment by bozo1209** [comment]
@AdnanArch 
Did you fix it?
Add this:
```java
import jakarta.persistence.Entity;
```
above class and ```@Entity``` annotation and check if it solves your issue

**Comment by AdnanArch** [comment]
@bozo1209  

I have added this but it is not recognizeable.

**Comment by bozo1209** [comment]
@AdnanArch 
Try to reload you project:
Intellij: open pom.xml -> right click -> maven -> reload project.
Rebuilt it:
Intellij: build -> rebuild project

Add this project to github and put link here, I will see if i can do something.

You can also recreate this project from scratch and see if problem is persistent.

 If you find a solution please leave a comment

**Comment by AdnanArch** [comment]
The problem was occurring due to the wrong version of JPA dependency that i added. So i removed that now the problem is fixed.
